import { SignInButton, useUser } from "@clerk/nextjs";
import Head from "next/head";

import { api } from "~/utils/api";

const CreatePostWizard = () => {
  const { user } = useUser();
  console.log("user");
  if (!user) return null;

  return (
    <div className="flex gap-4">
      <img
        src={user.imageUrl}
        alt="Profile Image Url"
        className="h-20 w-20 rounded-full"
      />
      <input placeholder="Type an update" className="grow bg-transparent p-4" />
    </div>
  );
};

export default function Home() {
  const user = useUser();

  const { data, isLoading } = api.post.getAll.useQuery();
  if (isLoading) return <div>Loading...</div>;
  if (!data) return <div>Something went wrong...</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center">
        <div className="h-screen w-full border-x border-slate-400 md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4">
            {!user.isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
            {user.isSignedIn && <CreatePostWizard />}
          </div>
          <div className="flex flex-col">
            {[...data]?.map((post) => (
              <div
                key={post.id}
                className="border-b border-slate-400 p-8 outline-none"
              >
                {post.content}
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
